#spring.application.name=identity-service
server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost/identity-service"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
